djangoProject/api/urls.py
#
from django.urls import path
from api import views


urlpatterns = [
    # URL パターンに <version> を含める
    path('books/', views.BookListAPIView.as_view()),
]

djangoProject/batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'
urlpatterns = [
    path('', views.BatchIndexView.as_view(), name='batch_index'),
]

djangoProject/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('welcome/', views.WelcomeView.as_view(), name='welcome'),
]

djangoProject/djangoProject/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include
from django.urls import path

from . import settings
from .settings import BASE_DIR

from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.SimpleRouter()
router.register('books', views.BookViewSet)


def home(request):
    if request.method == 'GET':
        msg = {'message': 'Hello there'}
        return render(request, os.path.join(BASE_DIR, 'templates/index.html'), msg)


# comment-out path('admin/', admin.site.urls)

urlpatterns = [
                  path('', home, name='home'),
                  path('home/', home, name='home_root'),
                  path('admin/', admin.site.urls),

                  # すべてのアクション （⼀覧・詳細 ・登録・更新・⼀部更新・ 削除） をまとめて追加
                  path('api/', include(router.urls)),
                  path('todo/', include('todo.urls')),
                  path('plot/', include('plot.urls')),
                  path('batch/', include('batch.urls')),
                  path('accounts/', include('allauth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns

djangoProject/todo/urls.py
#
import debug_toolbar
from django.template.defaulttags import url
from django.urls import include
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.TodoIndexView.as_view(), name='todo_index'),
    path('detail/<int:pk>', views.TodoDetailView.as_view(), name='todo_detail'),
    path('create/', views.TodoCreateView.as_view(), name='todo_create'),
    path('create_category/', views.TodoCreateView.as_view(), name='todo_create_category'),
    path('update/<int:pk>', views.TodoUpdateView.as_view(), name='todo_update'),
    path('delete/<int:pk>', views.TodoDeleteView.as_view(), name='todo_delete'),
    # url(r'^__debug__/', include(debug_toolbar.urls)),
    path('list/', views.TodoListAPIView.as_view()),
]

djangoProject/dashboard/models.py
from django.db import models

# Create your models here.

djangoProject/dashboard/views.py
from django.shortcuts import render

from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'home.html'


class WelcomeView(generic.TemplateView):
    template_name = 'welcome.html'

djangoProject/templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Django Lesson</a>
        <form class="d-flex md-7">
            <div class="d-flex justify-content-end">
            {% if user.is_authenticated != False %}
                <button type="button" class="btn btn-sm btn-success">User</button>
                <button type="button" class="btn btn-sm btn-outline-success">
                    {{ user.get_username }}
                </button>　
            {% else %}
                <a role="button" class="btn btn-sm btn-success" href="{% url 'account_login' %}">Login</a>　
            {% endif %}
                <input class="form-control mr-3" type="search" placeholder="検索ワードの入力" aria-label="検索"/>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </form>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div>　</div>
        <div class="col-lg-2 order-1">
            <div class="list-group">
                <ul class="list-group nav" id="menu-all_base" role="tablist">
                    <li class="list-group-item list-group-item-primary">基本</li>
                </ul>
                {% block todo_menu %}
                    <a href="{% url 'todo:todo_index' %}" class="list-group-item list-group-item-action">
                        <img src="{% static 'bootstrap-icons/icons/layout-text-window-reverse.svg' %}" alt="" width="24"
                             height="24"/>
                        　Todo CRUD
                    </a>
                {% endblock %}

                {% block batch_menu %}
                    <a href="{% url 'batch:batch_index' %}" class="list-group-item list-group-item-action">
                        <img src="{% static 'bootstrap-icons/icons/diagram-3.svg' %}" alt="" width="24" height="24"/>
                        　Batch</a>
                {% endblock %}

                <a href="{% url 'plot:plot_index' %}" class="list-group-item list-group-item-action">
                    <img src="{% static 'bootstrap-icons/icons/diagram-3.svg' %}" alt="" width="24" height="24"/>
                    　画像処理</a>
                <a href="{% url 'plot:plot_index' %}" class="list-group-item list-group-item-action">
                    <img src="{% static 'bootstrap-icons/icons/person-plus.svg' %}" alt="" width="24" height="24"/>
                    　Rest-API</a>
                <a href="#" class="list-group-item list-group-item-secondary">
                    <img src="{% static 'bootstrap-icons/icons/envelope.svg' %}" alt="" width="24" height="24"/>
                    　Lambda</a>
                <a role="button" class="btn  btn-sm btn-outline-primary" href="/auth/login/">ログイン</a>
                <a role="button" class="btn  btn-sm btn-outline-secondary" href="/auth/logout/">ログアウト</a>
            </div>
            <hr>
            <div>
                <ul class="list-group nav" id="menu-all" role="tablist">
                    <li class="list-group-item list-group-item-dark">機械学習・DL</li>
                    <li class="list-group-item list-group-item-action">可視化</li>
                    <li class="list-group-item list-group-item-action">回帰</li>
                    <li class="list-group-item list-group-item-action">分類</li>
                    <li class="list-group-item list-group-item-action">解析</li>
                    <li class="list-group-item list-group-item-action">NN</li>
                    <li class="list-group-item list-group-item-action">GA</li>
                </ul>
            </div>
        </div>
        {% block content %}
            <div class="col-lg-7 border order-2">
                センター・コンテンツ
            </div>
        {% endblock %}
        <div class="col-lg-3 order-3">
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">情報①</li>
                    <li class="list-group-item">情報②</li>
                    <li class="list-group-item">
                        <div class="card">
                            <div class="card-header">
                                カード・ヘッダー
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">タイトル</h5>
                                <p class="card-text">説明文</p>
                                <a href="#" class="btn btn-primary">リンク先ボタン</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div>　
</div>
<div class="border g-2">
    <div class="border">
        <div class="row justify-content-md-center">
            &copy2020 Happy IT Semi
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

djangoProject/templates/dashboard/home.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todoインデックス{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        <br/>
        ▶Todo一覧<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-info" href="{% url "todo:todo_create" %}">新規作成</a>
        <hr/>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>id</th>
                <th>Todo名</th>
                <th>カテゴリー</th>
                <th>内容</th>
                <th>期日</th>
                <th>作成日<br/>
                    更新日
                </th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>
            <tbody>
            {% for todo in object_list %}
                <tr>
                    <td>{{ todo.pk }}</td>
                    <td><a href="{% url 'todo:todo_detail' todo.pk %}"> {{ todo.name }} </a></td>
                    <td>{{ todo.category.name }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.due_date|date:"Y-m-j" }}</td>
                    <td> {{ todo.created_at|date:"Y-m-j" }}<br/>
                        {{ todo.updated_at|date:"Y-m-j" }}</td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_update' todo.pk %}">更新</a></td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_delete' todo.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>
        ・他のモデルからテーブル情報を読み取る：→Categoryクラス(categoryテーブル）<br/>
        ・contextオブジェクトを利用したselectの作成例<br>
        <select id="category_id" name="category" class="form-select" aria-label="カテゴリー">
            <option selected>カテゴリーの選択</option>
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat }}</option>
            {% endfor %}
        </select>
        <div>
            <form method="POST" action="{% url 'todo:todo_create_category' %}">
                {% csrf_token %}
                {{ form_non_field_errors }}
                <table class="table table-bordered table-sm">
                    {{ form2.as_table }}
                </table>
            </form>
        </div>

    </div>
{% endblock %}

djangoProject/templates/dashboard/index.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todoインデックス{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        <br/>
        ▶Todo一覧<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-info" href="{% url "todo:todo_create" %}">新規作成</a>
        <hr/>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>id</th>
                <th>Todo名</th>
                <th>カテゴリー</th>
                <th>内容</th>
                <th>期日</th>
                <th>作成日<br/>
                    更新日
                </th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>
            <tbody>
            {% for todo in object_list %}
                <tr>
                    <td>{{ todo.pk }}</td>
                    <td><a href="{% url 'todo:todo_detail' todo.pk %}"> {{ todo.name }} </a></td>
                    <td>{{ todo.category.name }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.due_date|date:"Y-m-j" }}</td>
                    <td> {{ todo.created_at|date:"Y-m-j" }}<br/>
                        {{ todo.updated_at|date:"Y-m-j" }}</td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_update' todo.pk %}">更新</a></td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_delete' todo.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>
        ・他のモデルからテーブル情報を読み取る：→Categoryクラス(categoryテーブル）<br/>
        ・contextオブジェクトを利用したselectの作成例<br>
        <select id="category_id" name="category" class="form-select" aria-label="カテゴリー">
            <option selected>カテゴリーの選択</option>
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat }}</option>
            {% endfor %}
        </select>
        <div>
            <form method="POST" action="{% url 'todo:todo_create_category' %}">
                {% csrf_token %}
                {{ form_non_field_errors }}
                <table class="table table-bordered table-sm">
                    {{ form2.as_table }}
                </table>
            </form>
        </div>

    </div>
{% endblock %}

djangoProject/templates/dashboard/welcome.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todoインデックス{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        <br/>
        ▶Todo一覧<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-info" href="{% url "todo:todo_create" %}">新規作成</a>
        <hr/>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>id</th>
                <th>Todo名</th>
                <th>カテゴリー</th>
                <th>内容</th>
                <th>期日</th>
                <th>作成日<br/>
                    更新日
                </th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>
            <tbody>
            {% for todo in object_list %}
                <tr>
                    <td>{{ todo.pk }}</td>
                    <td><a href="{% url 'todo:todo_detail' todo.pk %}"> {{ todo.name }} </a></td>
                    <td>{{ todo.category.name }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.due_date|date:"Y-m-j" }}</td>
                    <td> {{ todo.created_at|date:"Y-m-j" }}<br/>
                        {{ todo.updated_at|date:"Y-m-j" }}</td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_update' todo.pk %}">更新</a></td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_delete' todo.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>
        ・他のモデルからテーブル情報を読み取る：→Categoryクラス(categoryテーブル）<br/>
        ・contextオブジェクトを利用したselectの作成例<br>
        <select id="category_id" name="category" class="form-select" aria-label="カテゴリー">
            <option selected>カテゴリーの選択</option>
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat }}</option>
            {% endfor %}
        </select>
        <div>
            <form method="POST" action="{% url 'todo:todo_create_category' %}">
                {% csrf_token %}
                {{ form_non_field_errors }}
                <table class="table table-bordered table-sm">
                    {{ form2.as_table }}
                </table>
            </form>
        </div>

    </div>
{% endblock %}